### ISSUE TITLE
`list` command does not work by default

### ISSUE THREAD

**Issue by AGlass0fMilk** [ARMmbed/mbed-os-bluetooth-integration-testsuite#11]
When building with mbed-cli, the `list` command does not work for any BLE command suites available.

ie: Attempting `gap list` results in the following error message:

```
{"status": -1,"error": "invalid command name, you can get all the command name for this module by using the command 'list'"}
```

This is due to some missing configuration macros (maybe this is intended to be built with the new cmake-based build tools?)

**Comment by pan-** [comment]
cliapp was started before Mbed OS 5 and its configuration system. At the time you had to put macro definition in the `MACROS` sections. Thanks for raising this issue and a PR.
